export default {
    products: {
        products1: [
            {
                _id: '1',
                name: 'JABRA BIZ 1500 black Headphone ',
                image: 'Images/Image - 6.png',
                price: 45,
                brand: 'Brumer',
                rating: 4.5,
                numReviews: 10,
                countInStock: 6,
            },
            {
                _id: '2',
                name: 'obble Scent Travel Pack Explore 50ml',
                image: 'Images/Image - 7.png',
                price: 78,
                brand: 'Maxfox',
                rating: 2.5,
                numReviews: 23,
                countInStock: 22,
            },
            {
                _id: '3',
                name: 'Intensive Eye Cream with Vitamin C',
                image: 'Images/Image - 8.png',
                price: 95,
                brand: 'Curology',
                rating: 3.5,
                numReviews: 17,
                countInStock: 55,
            },
            {
                _id: '4',
                name: 'Spider Water Bottle Shaker',
                image: 'Images/Image - 9.png',
                price: 9,
                brand: 'Flomer',
                rating: 3.5,
                numReviews: 10,
                countInStock: 6,
            },
        ],
    
    
        products2: [
            {
                _id: '5',
                name: 'Canon EOS 80D DSLR Camera with 18-135mm',
                image: 'Images/Image - 10.png',
                price: 124,
                brand: 'Cannon',
                rating: 3.5,
                numReviews: 10,
                countInStock: 6,
            },
            {
                _id: '6',
                name: 'Flower Vase Island Display Merchandising',
                image: 'Images/Image - 11.png',
                price: 44,
                brand: 'Glumer',
                rating: 2.5,
                numReviews: 10,
                countInStock: 6,
            },
            {
                _id: '7',
                name: 'alancing Gel Cleanser Normal/Oily Skin 75ml',
                image: 'Images/Image - 12.png',
                price: 99,
                brand: 'Kettl',
                rating: 3.5,
                numReviews: 10,
                countInStock: 6,
            },
            {
                _id: '8',
                name: 'Male Running Outdoor Sports Shoes',
                image: 'Images/Image - 13.png',
                price: 23,
                brand: 'Nikie',
                rating: 4.5,
                numReviews: 10,
                countInStock: 6,
            },
    
        ],
        products3: [
            {
                _id: '9',
                name: 'JABRA BIZ 1500 black Headphone ',
                image: 'Images/Image - 15.png',
                price: 45,
                brand: 'Brumer',
                rating: 4.5,
                numReviews: 10,
                countInStock: 6,
            },
            {
                _id: '10',
                name: 'obble Scent Travel Pack Explore 50ml',
                image: 'Images/Image - 16.png',
                price: 78,
                brand: 'Maxfox',
                rating: 2.5,
                numReviews: 23,
                countInStock: 22,
            },
            {
                _id: '11',
                name: 'Intensive Eye Cream with Vitamin C',
                image: 'Images/Image - 17.png',
                price: 95,
                brand: 'Curology',
                rating: 3.5,
                numReviews: 17,
                countInStock: 55,
            },
            {
                _id: '12',
                name: 'Spider Water Bottle Shaker',
                image: 'Images/Image - 18.png',
                price: 9,
                brand: 'Flomer',
                rating: 3.5,
                numReviews: 10,
                countInStock: 6,
            },
        ],
    
    
        products4: [
            {
                _id: '13',
                name: 'Canon EOS 80D DSLR Camera with 18-135mm',
                image: 'Images/Image - 19.png',
                price: 124,
                brand: 'Cannon',
                rating: 3.5,
                numReviews: 10,
                countInStock: 6,
            },
            {
                _id: '14',
                name: 'Flower Vase Island Display Merchandising',
                image: 'Images/Image - 20.png',
                price: 44,
                brand: 'Glumer',
                rating: 2.5,
                numReviews: 10,
                countInStock: 6,
            },
            {
                _id: '15',
                name: 'alancing Gel Cleanser Normal/Oily Skin 75ml',
                image: 'Images/Image - 21.png',
                price: 99,
                brand: 'Kettl',
                rating: 3.5,
                numReviews: 10,
                countInStock: 6,
            },
            {
                _id: '16',
                name: 'Male Running Outdoor Sports Shoes',
                image: 'Images/Image - 22.png',
                price: 23,
                brand: 'Nikie',
                rating: 4.5,
                numReviews: 10,
                countInStock: 6,
            },
    
        ],
    
    },
}